name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  flutter_bloc: ^9.1.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  flutter_localizations:
    sdk: flutter
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSans(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSans(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSans(FaNum)_Bold.ttf
          weight: 600
    - family: Yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
          weight: 400